version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: saso123
      MYSQL_DATABASE: microservices
      MYSQL_USER: saso
      MYSQL_PASSWORD: saso123
    volumes:
      - mysql:/data/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql
    restart: unless-stopped
#  postgres:
#    container_name: postgres
#    image: postgres
#    environment:
#      POSTGRES_USER: superuser
#      POSTGRES_PASSWORD: saso123
#      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
#    ports:
#      - "5433:5433"
#    networks:
#      - postgres
#    restart: unless-stopped
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    restart: unless-stopped

networks:
  mysql:
    driver: bridge
#  postgres:
#    driver: bridge

volumes:
  mysql:
#  postgres:
#  pgadmin: